{% set name = "scikit-rf" %}
{% set version = "1.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c00ba602bf45ff3b368ccbb1ca93cbf0e18d0d5dfcff2591e0efacdff6d65a43

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=64
  run:
    - python
    - numpy >=1.21
    - scipy >=1.7
    - pandas >=1.1
    - typing-extensions
  run_constrained:
    # testspice
    - pyspice >=1.5
    # plot
    - matplotlib-base >=3.5
    # xlsx 
    - openpyxl >=3.0
    # netw 
    - networkx >=2.0
    # visa
    - pyvisa >=1.12
    - pyvisa-py >=0.6

# >   with pytest.raises(RuntimeWarning):
# E   Failed: DID NOT RAISE <class 'RuntimeWarning'>
# The test uses pytest.raises(RuntimeWarning) but warnings aren't exceptions—they need pytest.warns() instead.
{% set deselect_tests = " --deselect=skrf/tests/test_network.py::NetworkTestCase" %}
test:
  source_files:
    - skrf/tests
    - skrf/io/tests
    - doc
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media
  commands:
    - pip check
    - pytest -v skrf {{ deselect_tests }}
  requires:
    - pip
    - pytest >=7.0
    - pytest-mock >=3.10

about:
  home: https://scikit-rf.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Object Oriented Microwave Engineering.
  doc_url: https://scikit-rf.readthedocs.io
  description: |
    scikit-rf is an Open Source, BSD-licensed package for RF/Microwave
    engineering implemented in the Python programming language. It provides
    a modern, object-oriented library which is both flexible and scalable.
  dev_url: https://github.com/scikit-rf/scikit-rf

extra:
  recipe-maintainers:
    - arsenovic
