{% set version = "0.14.7" %}

package:
  name: scikit-rf
  version: {{ version }}

source:
  fn: scikit-rf-{{ version }}.zip
  url: https://github.com/scikit-rf/scikit-rf/archive/v{{ version }}.zip
  sha256: c8318102f7eb7971b1b57acd6a8524dd2357d2b8901836f7418c3abb51af87e2

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - ipython
    - numpy
    - scipy
    - matplotlib
    - six
    - future

test:
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media

about:
  home: http://www.scikit-rf.org
  license: BSD 3-Clause
  summary: 'Object Oriented Microwave Engineering.'
  doc_url: http://scikit-rf.readthedocs.io/
  dev_url: https://github.com/scikit-rf/scikit-rf

extra:
  recipe-maintainers:
    - arsenovic
