{% set version = "0.14.5" %}

package:
  name: scikit-rf
  version: {{ version }}

source:
  fn: scikit-rf-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scikit-rf/scikit-rf-{{ version }}.tar.gz
  sha256: 43f734a28d460a8f005bd875e0c0ea3dd9c5dfc6bc389f116b8dde11cd38518d

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - pandas
    - ipython
    - numpy
    - scipy
    - matplotlib
    - six
    - future

test:
  imports:
    - apps
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media
    - skrf.notebook
    - skrf.vi
    - skrf.vi.scpi

about:
  home: http://www.scikit-rf.org
  license: BSD 3-Clause
  summary: 'Object Oriented Microwave Engineering.'
  doc_url: http://scikit-rf.readthedocs.io/
  description: |
    scikit-rf is an Open Source, BSD-licensed package for RF/Microwave
    engineering implemented in the Python programming language. It provides
    a modern, object-oriented library which is both flexible and scalable.
  doc_url: http://scikit-rf.readthedocs.org/en/latest/
  doc_source_url: https://github.com/scikit-rf/scikit-rf/blob/master/doc/source/index.rst
  dev_url: https://github.com/scikit-rf/scikit-rf

extra:
  recipe-maintainers:
    - arsenovic
