{% set version = "1.2.0" %}
{% set sha256 = "870ac9f461ebcc9514d861385787ac4be84636ab2b1eba3b91e096ad4d9c59c2" %}

package:
  name: scikit-rf
  version: {{ version }}


source:
  fn: scikit-rf-{{ version }}.tar.gz
  # For some reason, 0.17.0 dropped the `.0` patch component from its GitHub
  # archive names, so we need to munge the version string to avoid getting a
  # 404 when downloading the sources.  Note that conda-forge set its conda
  # package version to "0.17", but we are not doing that for defaults because
  # we want our conda package's version string to match the version string the
  # upstream authors published to PyPI.
  url: https://github.com/scikit-rf/scikit-rf/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  # Upstream has seemingly not put any effort into fixing the broken C
  # components in `skrf.src`, so we may as well turn treat this as a pure
  # Python package like conda-forge has done since v0.14.9.
  skip: True  # [py<38]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - pandas >=1.1
    - numpy >=1.2.1
    - scipy >=1.7

test:
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://scikit-rf.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Object Oriented Microwave Engineering.'
  doc_url: https://scikit-rf.readthedocs.io/
  description: |
    scikit-rf is an Open Source, BSD-licensed package for RF/Microwave
    engineering implemented in the Python programming language. It provides
    a modern, object-oriented library which is both flexible and scalable.
  dev_url: https://github.com/scikit-rf/scikit-rf

extra:
  recipe-maintainers:
    - arsenovic
