{% set version = "1.8.0" %}
{% set sha256 = "c00ba602bf45ff3b368ccbb1ca93cbf0e18d0d5dfcff2591e0efacdff6d65a43" %}

package:
  name: scikit-rf
  version: {{ version }}

source:
  fn: scikit-rf-{{ version }}.tar.gz
  # For some reason, 0.17.0 dropped the `.0` patch component from its GitHub
  # archive names, so we need to munge the version string to avoid getting a
  # 404 when downloading the sources.  Note that conda-forge set its conda
  # package version to "0.17", but we are not doing that for defaults because
  # we want our conda package's version string to match the version string the
  # upstream authors published to PyPI.
  url: https://github.com/scikit-rf/scikit-rf/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # Upstream has seemingly not put any effort into fixing the broken C
  # components in `skrf.src`, so we may as well turn treat this as a pure
  # Python package like conda-forge has done since v0.14.9.
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=64
  run:
    - python
    - pandas >=1.1
    - numpy >=1.21
    - scipy >=1.7
    - typing_extensions
  run_constrained:
    - networkx >=2.0
    - matplotlib-base >=3.5
    - PyVISA >=1.12
    - pyvisa-py >=0.6
    - openpyxl >=3.0

test:
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://scikit-rf.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Object Oriented Microwave Engineering.
  doc_url: https://scikit-rf.readthedocs.io/
  description: |
    scikit-rf is an Open Source, BSD-licensed package for RF/Microwave
    engineering implemented in the Python programming language. It provides
    a modern, object-oriented library which is both flexible and scalable.
  dev_url: https://github.com/scikit-rf/scikit-rf

extra:
  recipe-maintainers:
    - arsenovic
