travis:
  secure:
    BINSTAR_TOKEN: pQdKqyiuQJe3kViINcti1Otxg96OGxTsYV53NLfRy+8qlSMWbLUlfYy/8EU9jgbLST5NznGgUSk7yyrezAWXSnp9uHaq99UBtlpaIXP0EJ0lSfTDdo4xomHhp9XE7VADCQcv68EIF24tcmhlfBX1cg+KJkkv68DpM4amgas2cQTYCjNpmt415hu8vgTn3nzEBOIAQl8N+CMjt6BDD8DpbsNQUJ5zszT6Fi8uQx7t0QxBP8sbCOJMDDXNyKATstfo36l2h+J2+M38UspWsgjUUQ/TA6sJyWWFpMkRWZc9VoKbpwzT0E1ZHb9SaMokq649bHh+Uc7WjRPKCIDHBGLSuUI+UErdbnkb15/VyYR86ks/TD7uqWx94kWSYbccMttukCt6Qmxt/OjdWOS9Qw36ST/R1CRPaOFRc+7+kmcNdn4XK0Ce58iUGgh3qcUIMN2PPQXNdNV1iWiBObPRPKb5jYa+AxRf62OqM867n0ChtOgsL8CyztKDCUk8tFeW1+2WPLpGxP79zEhE0mf93bpTJ+dFD0sCudQf2P6MvERpl7b95sWKSrpFmZmDae0WsmIf8+o7y+fE7CCNgt6/zpZM7glxhDUUggSKDny89idEfxPEAkiXLogcy0jIkc0N1rmBDPVPIaJ+12qZ/K+t87CbS+6dRrxsUQbDWSpzjY2c7WM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
